apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: read-only
rules:
- apiGroups: ["*"]
  resources:
    - nodes
    - namespaces
    - services
    - pods
    - ingresses
    - persistentvolumeclaims
    - persistentvolumes
    - storageclasses
    - endpoints
    - bindings
    - events
    - limitranges
    - pods/exec
    - pods/attach
    - pods/portforward
    - namespaces/status
    - pods/log
    - pods/status
    - replicationcontrollers/status
    - resourcequotas
    - resourcequotas/status
  verbs:
  - get
  - list
  - watch
  - exec
  - describe
- apiGroups:
  - extensions
  resources:
    - daemonsets
    - deployments
    - deployments/scale
    - services
    - ingresses
    - networkpolicies
    - replicasets
    - replicasets/scale
    - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - services
    - ingresses
    - replicasets/scale
    - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - get
    - list
    - watch
- apiGroups:
     - networking.k8s.io
  resources:
     - networkpolicies
  verbs:
     - get
     - list
     - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - clusterroles
    - roles
    - rolebindings
  verbs:
    - get
    - list
    - watch
