apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-nginx-argodemo-
commonLabels:
  apptype: nginx-argodemo
  envtype: production
bases:
- ../../../base
images:
- name: argodemo-image
  newName: nginx
  newTag: 1.21.1-perl
patchesStrategicMerge:
- increase_replicas.yaml
- port_service.yaml
resources:
- ingress.yaml
#- alb.yaml
patchesJson6902:
- target:
    kind: Deployment
    name: org
  path: patch.yaml
