apiVersion: apps/v1
kind: Deployment
metadata:
  name: org
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 65
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      app: org
  template:
    metadata:
      labels:
        app: org
    spec:
      containers:
      - image: argodemo-image
        name: application
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: "128Mi"
            cpu: "500m"
